### PR TITLE
Make CCV2 Article page content dynamic

### PR DESCRIPTION
**Pull request by ljcoulson**
These changes allow for the creation of an Article page that has the look and feel of the CCV2 Article Page design and uses dynamic content.

Screenshot 2022-02-25 at 13 43 30

### CODE REVIEW

**Comment by ajtucker** [comment]
Hey @ljcoulson, Jenkins is reporting a failed test for this. Does https://github.com/GSS-Cogs/dd-cms/pull/111/checks?check_run_id=5393684640 mean that the snapshot needs to be updated?

**Comment by nosnickid** [comment]
Merged main just to try it out. 

Also took volto-climatechange-elements out of package.json. package.json is used to deploy climate-1.ukstats.dev. See #106 for a bit more on why.

**Comment by ajtucker** [comment]
> Merged main just to try it out.
> 
> Also took volto-climatechange-elements out of package.json. package.json is used to deploy climate-1.ukstats.dev. See #106 for a bit more on why.

Good spot.

**Comment by ajtucker** [comment]
@ljcoulson , I did have a go at this locally: I added `cc_preview` and `cc_preview2` as views on the Document/Page content type, then created a new page and enabled the `cc_preview2` view.

The first error was about not having any related content, so I added something in the sidebar, but then got an error about that content not having some property.

Could you jot down some brief instructions on setting things up to test, so I can see where I've gone wrong?

**Comment by ljcoulson** [comment]
@ajtucker 

Steps to create Article page

- Go here first - http://localhost:8080/Plone/portal_types/Document and add 'cc_preview' to the 'Available view methods' text area and save.
- Make sure that 'volto-climatechange-elements' is added to addons and workspaces in package.json
- Create a new page in volto using the 'Page' content type
- In the right hand side menu in volto make sure to populate these fields - 'Title', 'Summary', 'Related Items', 'Publishing date' and 'Authors'.
- For the body content use voltos 'HTML' block and just add some content wrapped in P, UL, H2-H4 tags etc
- Save the document and make sure 'cc_preview' is selected in the View field.

**Comment by ljcoulson** [comment]
@ajtucker I have fixed the issue you were getting with the `relatedItems` error message. This was a minor issue with `cc_preview2` which isn't a dynamic page yet. If you use this view now you should be able to see a page like the one below:
Screenshot 2022-03-14 at 11 42 21

To test the dynamic ccv2 article page you need to use the `cc_preview` view.

**Review by ajtucker — APPROVED** [review]
I got this to work locally using the ["full stack dev"](/GSS-Cogs/dd-cms/blob/main/docs/deployment.md) approach.

I've not yet managed to figure out why it doesn't seem to work in a the deployment, but will raise a separate issue for this.

**Pull request merged**
