### PR TITLE
Issue 468/Dashboard Menus

### LINKED ISSUE #468: Dashboard List to be populated from API Call

### PR DESCRIPTION
**Pull request by anojperera**
This closes #468.

* Overridden header component changed to a function to make it easy for using react hooks.
* API call implemented to get the dashboard items.
* Added null handler to SuperNavigationHeader Component 

Screenshot 2022-07-16 at 22 10 10

### CODE REVIEW

**Comment by ajtucker** [comment]
I think we're potentially doing this in a bit of a round about way...

The existing Navigation.jsx component that we override uses the `@navigation` REST API https://plonerestapi.readthedocs.io/en/latest/navigation.html, which in turn uses the catalogue to quickly compute a site map of a given depth.

E.g., something like
```
curl -i -X GET 'https://staging.climate-change.data.gov.uk/api/@navigation?expand.navigation.depth=2' -H "Accept: application/json"
```
is already run for us and used to create the navbar. Can we pass these results to the super navbar and avoid the more expensive `getFolderishContent` call?

**Comment by charlesons** [comment]
Couple of suggestions to check and potentially tweak

1. The Figma design shows the dashboard summary text under each dashboard page link:



2. Vertical spacing between dashboard items looks a bit larger than in Figma

3. Dashboard menu items  seem not to be available on first load. Opening up the articles page and then going back to dashboard items seems then to make the dashboard items available.

**Comment by charlesons** [comment]
@gareth-lewis @garethlewis-ons, should the footer section with 'About the portal' and 'Datasets' be present here?

**Comment by anojperera** [comment]
@ajtucker, I've updated the component to get the data from the Redux which is populated from an earlier call.

**Pull request merged**
