### PR TITLE
Issue 696/table of contents component

### LINKED ISSUE #696: Table of contents component
Create a responsive table of contents component

The design for the TOC component is here (in the article the UK's climate is changing): https://www.figma.com/file/n61a8x7kKnkriF7b9XAADl/Climate-Change?node-id=1374%3A11462

- [x] The component will be a view that can be applied to an existing page of content
- [x] The TOC will extract its content from the page content hierarchy 
- [x] Clicking on a link in the TOC will scroll the page to the linked content
- [x] The page will have a one-third, two-thirds layout with the TOC floating on the left and the main page content on the right
- [ ] 66% text width styling will not apply to the text (as it does on full width pages)
- [x] There will be a breakpoint of `768px` where the TOC switches from the left of the page to the top of the page 
- [x] When in this small viewport mode there will be a `back to contents` link at the bottom of each section that when clicked returns the user to the TOC at the top

Notes:

To select the view the content creator would click on the More (...) icon and apply the page view 'Page with TOC' which would show as an extra option in the list below.

### PR DESCRIPTION
**Pull request by StRhys**
I found the only way to get the 'position: sticky' on the ToC is to set a height on its parent. When using 100% it would not scroll with the page. So getting the height of the parent's parent container via ref and setting it via that. There might be an easier way via just css but I'm unsure of it.

closes #696

### CODE REVIEW

**Review by charlesons — COMMENTED** [review]
Did an initial pair review with @StRhys and we identified some potential tweaks to complete the ticket:

- Minor issue with the vertical spacing lost between sections of the main content
- Adjustment of the positioning logic for the `back to contents` buttons to be after each top section or second level section (except where a second level section follows immediately on from a top level section). 
- Possible issue with the viewport width measurement method which was registering a change in the 801px breakpoint at 630px. Potentially could use [react-hook/resize-observer](https://www.npmjs.com/package/@react-hook/resize-observer) to measure the viewport width instead.

**Comment by StRhys** [comment]
regarding 'breakpoint fix for 801px', by default govuk designs uses 'em' units for min-width/max-width css, so the breakpoint would change between browsers. 801px would be the breakpoint on chrome but safari would use 630px, etc.

**Comment by StRhys** [comment]
alignment fix
previous
image

new
image

**Review by charlesons — APPROVED** [review]
We reviewed the tweaks and all looking great!

**Pull request merged**
